@host=http://localhost:5244


GET  {{host}}/dummy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNDIwNDhiMy1lNmEzLTQ0MmYtYTE4Mi1hOTgzZDc4NWRhNGUiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiYTY4ZjJhMTMtOTkxZS00YjYxLWI1NTctYTJmNTg4MDNkNTU1IiwiZXhwIjoxNzExMDIwMTY4LCJpc3MiOiJCb29rZmxpeCIsImF1ZCI6IkJvb2tmbGl4In0.V_Dal9rIYmCX-GzpMsnl8FpXeQCOg4vlQq8IHz1l5ow
