@host=http://localhost:5244

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John3",
    "lastName": "Doe3",
    "email": "johndoe3@gmail.com",
    "password": "pass3"
}