@host=http://localhost:5244

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John2",
    "lastName": "Doe2",
    "email": "johndoe2@gmail.com",
    "password": "pass2"
}