@host=http://localhost:5244

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "Johndoe@gmail.com",
    "password": "Welcome@123"
}