@host=http://localhost:5244
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6ImY4NDc5NDE0LTMyMTEtNDg2OC1hNjExLWY3OTIxMjA4MjExNCIsImV4cCI6MTcxMjE3NDQzMiwiaXNzIjoiQm9va2ZsaXgiLCJhdWQiOiJCb29rZmxpeCJ9.5oW-3YzeYLaAGwpkvBaFiKFWj9LC79g7GHdE7OtA1oA
@bookId=1

POST {{host}}/books/{{bookId}}/reviews
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rating": 3.1,
    "bookId": 4
}
