@host=http://localhost:5244
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZ2l2ZW5fbmFtZSI6IkpvaG4zIiwiZmFtaWx5X25hbWUiOiJEb2UzIiwianRpIjoiZmI1NDhjMWUtOGUyYy00OThlLWI0Y2MtMjA2YjJmYTBkNDI2IiwiZXhwIjoxNzEyMjYyMDI1LCJpc3MiOiJCb29rZmxpeCIsImF1ZCI6IkJvb2tmbGl4In0.Nf3VBvdHh7fSonW11-rVUcz1YZWd3r80HWgJp-jknXM
@bookId=1

POST {{host}}/books/{{bookId}}/reviews
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rating": 3.3,
    "bookId": 2
}
