@host=http://localhost:5244
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6IjEzOWVjZWU2LTIzOWMtNDA4My1iOTI0LWQzMDg0OWM2OTUxNiIsImV4cCI6MTcxMTgyOTM4MywiaXNzIjoiQm9va2ZsaXgiLCJhdWQiOiJCb29rZmxpeCJ9.iDfYJchySjDZHa04vCwBx0SEM_8R98NjKKfrZgSJzyI

POST {{host}}/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "The Great Gatsby",
    "description": "Best description ever",
    "authorId": 1,
    "genres": [
        {
            "genreId": 1
        },
        {
            "genreId": 2
        },
        {
            "genreId": 3
        }
    ]
}