@host=http://localhost:5244
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZ2l2ZW5fbmFtZSI6IkpvaG4yIiwiZmFtaWx5X25hbWUiOiJEb2UyIiwianRpIjoiMjEwYmY3ZWMtNDAyMC00NjViLThkOTktNzAzNTdkMWFmMjI0IiwiZXhwIjoxNzEyMjYxNzcwLCJpc3MiOiJCb29rZmxpeCIsImF1ZCI6IkJvb2tmbGl4In0.KebRXExkPe_XYiQ-szq0VKFzwrVqFAT0HIFwqAKe86k

GET {{host}}/books?authorId=1
Content-Type: application/json
Authorization: Bearer {{token}}

{
}